import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Sparkles,
  Bot,
  TrendingUp,
  TrendingDown,
  Target,
  ShieldAlert,
  Bell,
  CheckCircle2,
  ExternalLink,
  Plus,
  Loader2,
  RefreshCw,
  Zap,
  Info,
  DollarSign,
  Compass,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import {
  MacroStockPick,
  MacroStockAgentResponse,
  useGenerateMacroStockPicks,
} from '@/services/economicCycleService';
import { useCreateTradeIdea } from '@/services/ideaService';
import { createAlert } from '@/services/alertService';
import { toast } from 'sonner';

interface MacroStockAgentModalProps {
  isOpen: boolean;
  onClose: () => void;
  initialData?: MacroStockAgentResponse | null;
  onNavigateToResearch?: (symbol: string) => void;
}

export function MacroStockAgentModal({
  isOpen,
  onClose,
  initialData,
  onNavigateToResearch,
}: MacroStockAgentModalProps) {
  const stockAgentMutation = useGenerateMacroStockPicks();
  const createIdeaMutation = useCreateTradeIdea();

  const [stockData, setStockData] = useState<MacroStockAgentResponse | null>(initialData || null);
  const [savedIdeaSymbols, setSavedIdeaSymbols] = useState<Set<string>>(new Set());
  const [savedAlertSymbols, setSavedAlertSymbols] = useState<Set<string>>(new Set());
  const [customPrompt, setCustomPrompt] = useState('');

  // Re-generate picks
  const handleRegenerate = async () => {
    try {
      const data = await stockAgentMutation.mutateAsync(customPrompt || undefined);
      setStockData(data);
      toast.success(`Generated ${data.picks.length} macro-aligned stock ideas!`);
    } catch (err: any) {
      toast.error(`Agent failed: ${err.message}`);
    }
  };

  // 1-Click: Save Pick as Trade Idea
  const handleSaveAsIdea = async (pick: MacroStockPick) => {
    try {
      await createIdeaMutation.mutateAsync({
        title: `${pick.symbol} - ${pick.industry} Macro Regime Setup`,
        symbol: pick.symbol,
        type: pick.sentiment,
        timeframe: pick.timeframe,
        entryPrice: pick.entryPrice,
        targetPrice: pick.targetPrice,
        stopLoss: pick.stopLoss,
        confidenceScore: pick.confidenceScore,
        source: 'AI_AGENT',
        tags: `Macro,${pick.sector.replace(/\s+/g, '')},${stockData?.cycleStage || 'LateCycle'}`,
        content: `### 🌐 Macro Economic Cycle Thesis\n\n**Company**: ${pick.companyName} (${pick.symbol})\n**Sector/Industry**: ${pick.sector} • ${pick.industry}\n**Stance**: \`${pick.stance}\`\n\n#### 🎯 Catalyst Thesis\n${pick.macroCatalystThesis}\n\n#### 📐 Cycle Alignment Rationale\n${pick.cycleAlignmentRationale}\n\n#### ⚠️ Key Risk Factors\n${pick.keyRisks.map((r) => `- ${r}`).join('\n')}\n\n---\n*Generated by AI Macro Economic Cycle Stock Agent.*`,
      });

      setSavedIdeaSymbols((prev) => new Set(prev).add(pick.symbol));
      toast.success(`Saved ${pick.symbol} to Trading Ideas!`, {
        description: 'Viewable in your Ideas Pipeline and ready for trade structuring.',
      });
    } catch (err: any) {
      toast.error(`Failed to save idea: ${err.message}`);
    }
  };

  // 1-Click: Set Price Alerts for Pick
  const handleSetAlerts = async (pick: MacroStockPick) => {
    try {
      // 1. Entry alert
      await createAlert({
        symbol: pick.symbol,
        targetPrice: pick.entryPrice,
        condition: pick.sentiment === 'BULLISH' ? 'BELOW' : 'ABOVE',
        notes: `[Macro Entry] ${pick.symbol} (${pick.stance}) at $${pick.entryPrice.toFixed(2)}`,
      });

      // 2. Target alert
      if (pick.targetPrice) {
        await createAlert({
          symbol: pick.symbol,
          targetPrice: pick.targetPrice,
          condition: pick.sentiment === 'BULLISH' ? 'ABOVE' : 'BELOW',
          notes: `[Macro Target] Take profit on ${pick.symbol} at $${pick.targetPrice.toFixed(2)}`,
        });
      }

      // 3. Stop loss alert
      if (pick.stopLoss) {
        await createAlert({
          symbol: pick.symbol,
          targetPrice: pick.stopLoss,
          condition: pick.sentiment === 'BULLISH' ? 'BELOW' : 'ABOVE',
          notes: `[Macro Stop] Invalidation stop for ${pick.symbol} at $${pick.stopLoss.toFixed(2)}`,
        });
      }

      setSavedAlertSymbols((prev) => new Set(prev).add(pick.symbol));
      toast.success(`Set 3 price alerts for ${pick.symbol}!`, {
        description: `Entry ($${pick.entryPrice}), Target ($${pick.targetPrice}), and Stop ($${pick.stopLoss}).`,
      });
    } catch (err: any) {
      toast.error(`Failed to set alerts: ${err.message}`);
    }
  };

  // Bulk Save All Picks to Trade Ideas
  const handleBulkSaveIdeas = async () => {
    if (!stockData?.picks) return;
    let count = 0;

    for (const pick of stockData.picks) {
      if (!savedIdeaSymbols.has(pick.symbol)) {
        try {
          await createIdeaMutation.mutateAsync({
            title: `${pick.symbol} - ${pick.industry} Macro Setup`,
            symbol: pick.symbol,
            type: pick.sentiment,
            timeframe: pick.timeframe,
            entryPrice: pick.entryPrice,
            targetPrice: pick.targetPrice,
            stopLoss: pick.stopLoss,
            confidenceScore: pick.confidenceScore,
            source: 'AI_AGENT',
            tags: `Macro,${pick.sector.replace(/\s+/g, '')}`,
            content: `### 🌐 Macro Economic Cycle Thesis\n\n**Company**: ${pick.companyName} (${pick.symbol})\n**Sector**: ${pick.sector} • ${pick.industry}\n\n#### 🎯 Catalyst\n${pick.macroCatalystThesis}\n\n#### 📐 Cycle Alignment\n${pick.cycleAlignmentRationale}`,
          });
          setSavedIdeaSymbols((prev) => new Set(prev).add(pick.symbol));
          count++;
        } catch {
          // continue
        }
      }
    }

    if (count > 0) {
      toast.success(`Successfully saved ${count} macro trade ideas to your Ideas Station!`);
    } else {
      toast.info('All ideas already saved.');
    }
  };

  const picks = stockData?.picks || [];

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[950px] max-h-[92vh] flex flex-col p-0 gap-0 overflow-hidden bg-card/95 backdrop-blur-2xl border border-border/80 shadow-2xl">
        {/* Header */}
        <DialogHeader className="p-6 pb-4 border-b border-border/50 bg-accent/20">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-amber-500/20 via-primary/20 to-purple-500/20 border border-amber-500/40 flex items-center justify-center text-amber-400 font-black shadow-lg">
                <Compass className="w-6 h-6 text-amber-300 animate-spin-slow" />
              </div>
              <div>
                <div className="flex items-center gap-2 flex-wrap">
                  <DialogTitle className="text-xl font-black tracking-tight text-foreground">
                    Macro Regime Stock Selection Agent
                  </DialogTitle>
                  {stockData?.stageName && (
                    <Badge variant="outline" className="text-xs font-bold bg-primary/10 text-primary border-primary/30 font-mono">
                      {stockData.stageName}
                    </Badge>
                  )}
                </div>
                <DialogDescription className="text-xs text-muted-foreground mt-0.5">
                  High-conviction stock opportunities engineered to capitalize on the active economic cycle stage and industry tailwinds.
                </DialogDescription>
              </div>
            </div>

            <div className="flex items-center gap-2 self-start sm:self-auto">
              <Button
                variant="outline"
                size="sm"
                onClick={handleRegenerate}
                disabled={stockAgentMutation.isPending}
                className="text-xs gap-1.5 h-8 font-semibold"
              >
                <RefreshCw className={cn("w-3.5 h-3.5", stockAgentMutation.isPending && "animate-spin text-primary")} />
                <span>Re-Synthesize</span>
              </Button>
            </div>
          </div>
        </DialogHeader>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-5 scrollbar-thin">
          {stockAgentMutation.isPending ? (
            <div className="py-20 flex flex-col items-center justify-center gap-3 text-center">
              <Loader2 className="w-8 h-8 animate-spin text-amber-400" />
              <p className="text-sm font-bold text-foreground">
                Macro Stock Agent is filtering the universe for regime-aligned leaders...
              </p>
              <p className="text-xs text-muted-foreground max-w-md">
                Screening for pricing power, low refinancing risk, sovereign capex tailwinds, and asymmetric risk/reward setups.
              </p>
            </div>
          ) : picks.length > 0 ? (
            <div className="space-y-4">
              {/* Executive Theme Banner */}
              {stockData?.themeOverview && (
                <div className="p-3.5 rounded-2xl bg-amber-500/10 border border-amber-500/30 text-xs text-amber-200/90 leading-relaxed flex items-start gap-2.5">
                  <Info className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold text-amber-300 block mb-0.5">Regime Selection Strategy</span>
                    {stockData.themeOverview}
                  </div>
                </div>
              )}

              {/* Grid of Stock Opportunities */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {picks.map((pick) => {
                  const isIdeaSaved = savedIdeaSymbols.has(pick.symbol);
                  const isAlertSaved = savedAlertSymbols.has(pick.symbol);

                  return (
                    <div
                      key={pick.id}
                      className="p-4 rounded-2xl bg-card/60 hover:bg-card/90 border border-border/70 hover:border-primary/40 transition-all shadow-md space-y-3 flex flex-col justify-between"
                    >
                      {/* Top Row: Symbol, Badges, ROI */}
                      <div>
                        <div className="flex items-start justify-between gap-2">
                          <div className="flex items-center gap-2.5">
                            <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/30 flex items-center justify-center font-mono font-black text-sm text-primary">
                              {pick.symbol.slice(0, 4)}
                            </div>
                            <div>
                              <div className="flex items-center gap-1.5 flex-wrap">
                                <span className="font-black text-base text-foreground font-mono">
                                  {pick.symbol}
                                </span>
                                <Badge variant="outline" className="text-[10px] font-mono font-bold bg-slate-900 border-border/60">
                                  ${pick.currentPrice.toFixed(2)}
                                </Badge>
                                <Badge
                                  variant="outline"
                                  className={cn(
                                    "text-[9px] font-mono font-bold px-1.5 py-0 h-4",
                                    pick.stance === 'STRONG_BUY' ? "bg-emerald-500/15 text-emerald-400 border-emerald-500/30" :
                                    pick.stance === 'TACTICAL_LONG' ? "bg-cyan-500/15 text-cyan-400 border-cyan-500/30" :
                                    "bg-purple-500/15 text-purple-400 border-purple-500/30"
                                  )}
                                >
                                  {pick.stance.replace('_', ' ')}
                                </Badge>
                              </div>
                              <p className="text-xs text-muted-foreground truncate max-w-[200px]">
                                {pick.companyName}
                              </p>
                            </div>
                          </div>

                          <div className="text-right shrink-0">
                            <span className="text-[10px] uppercase font-bold text-emerald-400 block font-mono">
                              +{pick.potentialROI}% Target
                            </span>
                            <span className="text-[10px] font-mono text-muted-foreground block">
                              R:R {pick.riskRewardRatio}
                            </span>
                          </div>
                        </div>

                        {/* Sector & Industry */}
                        <div className="flex items-center gap-2 mt-2 text-[11px] text-muted-foreground">
                          <Badge variant="secondary" className="text-[9.5px] font-semibold bg-accent/60 text-muted-foreground">
                            {pick.sector}
                          </Badge>
                          <span className="truncate">{pick.industry}</span>
                        </div>

                        {/* Levels Strip */}
                        <div className="grid grid-cols-3 gap-2 p-2 rounded-xl bg-slate-900/60 border border-border/40 text-xs font-mono mt-2.5">
                          <div>
                            <span className="text-[9.5px] text-muted-foreground block font-sans">Entry Limit</span>
                            <span className="font-bold text-cyan-300">${pick.entryPrice.toFixed(2)}</span>
                          </div>
                          <div>
                            <span className="text-[9.5px] text-emerald-400 block font-sans">Target</span>
                            <span className="font-bold text-emerald-400">${pick.targetPrice.toFixed(2)}</span>
                          </div>
                          <div>
                            <span className="text-[9.5px] text-rose-400 block font-sans">Stop Loss</span>
                            <span className="font-bold text-rose-400">${pick.stopLoss.toFixed(2)}</span>
                          </div>
                        </div>

                        {/* Catalyst Thesis */}
                        <div className="mt-2.5 space-y-1 text-xs">
                          <p className="text-foreground/90 font-medium leading-snug">
                            {pick.macroCatalystThesis}
                          </p>
                          <p className="text-[11px] text-muted-foreground leading-snug">
                            <strong className="text-foreground/70">Cycle Rationale:</strong> {pick.cycleAlignmentRationale}
                          </p>
                        </div>
                      </div>

                      {/* Action Buttons */}
                      <div className="flex items-center justify-between gap-2 pt-3 border-t border-border/40 mt-3">
                        <div className="flex items-center gap-1.5">
                          {onNavigateToResearch && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => {
                                onNavigateToResearch(pick.symbol);
                                onClose();
                              }}
                              className="h-7 text-[11px] px-2 text-muted-foreground hover:text-foreground"
                            >
                              <ExternalLink className="w-3 h-3 mr-1" /> Research
                            </Button>
                          )}
                        </div>

                        <div className="flex items-center gap-1.5">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => handleSetAlerts(pick)}
                            disabled={isAlertSaved}
                            className="h-7 text-[11px] px-2 text-amber-300 border-amber-500/30 hover:bg-amber-500/10 font-bold"
                          >
                            <Bell className="w-3 h-3 mr-1" />
                            {isAlertSaved ? 'Alerts Set' : 'Set Alerts'}
                          </Button>

                          <Button
                            size="sm"
                            onClick={() => handleSaveAsIdea(pick)}
                            disabled={isIdeaSaved || createIdeaMutation.isPending}
                            className="h-7 text-[11px] px-2.5 bg-primary text-primary-foreground font-bold shadow-sm"
                          >
                            {isIdeaSaved ? (
                              <><CheckCircle2 className="w-3 h-3 mr-1" /> Saved</>
                            ) : (
                              <><Plus className="w-3 h-3 mr-1" /> Save Idea</>
                            )}
                          </Button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          ) : (
            <div className="text-center py-12 space-y-3">
              <p className="text-sm font-bold text-muted-foreground">Click below to synthesize macro regime stock opportunities.</p>
              <Button onClick={handleRegenerate} className="text-xs font-bold gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-amber-300" /> Synthesize Regime Stock Ideas
              </Button>
            </div>
          )}
        </div>

        {/* Footer */}
        <DialogFooter className="p-4 border-t border-border/50 bg-accent/10 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="text-xs text-muted-foreground font-mono">
            {picks.length > 0 && `${picks.length} macro-aligned opportunities ready for execution`}
          </div>

          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" onClick={onClose} className="text-xs">
              Close
            </Button>

            {picks.length > 0 && (
              <Button
                onClick={handleBulkSaveIdeas}
                disabled={createIdeaMutation.isPending}
                className="bg-gradient-to-r from-amber-600 via-primary to-purple-600 hover:opacity-95 text-white font-bold text-xs shadow-md gap-1.5 px-4"
              >
                <Plus className="w-3.5 h-3.5" /> Save All to Trading Ideas
              </Button>
            )}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
